# This is a basic workflow to help you get started with Actions

name: TEST

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "HttpWorkerServer" ]
  pull_request:
    branches: [ "HttpWorkerServer" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # 1. 리포지토리 클론
      - uses: actions/checkout@v4

      # 2. 실행 중인 서버 확인 및 종료
      - name: Check and terminate existing server
        run: |
          PORT=8080  # 서버가 사용하는 포트 번호
          PID=$(lsof -t -i:$PORT || :)  # 포트에 바인딩된 프로세스 ID 확인  실패를 무시
          if [ ! -z "$PID" ]; then
            echo "Server is already running on port $PORT. Terminating..."
            kill -9 $PID  # 실행 중인 서버 종료
          else
            echo "No server is running on port $PORT."
          fi

      # 3. 의존성 설치
      - run: bun install

      # 4. pm2 실행
      - name: Start server with PM2
        run: pm2 reload index.ts
